version: '3'

services:
  bosted-db:
    image: mysql:latest
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=bostedpassword
      - MYSQL_DATABASE=bostedDB
      - MYSQL_USER=bosteduser
      - MYSQL_PASSWORD=bostedpassword
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u bosteduser -pbostedpassword" ]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      bosted-network:

  bosted:
    image: "bosted-image:latest"
    build:
      context: ./Bosted
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      bosted-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://bosted-db:3306/bostedDB
      - SPRING_DATASOURCE_USERNAME=bosteduser
      - SPRING_DATASOURCE_PASSWORD=bostedpassword
    networks:
      - zookeeper-kafka
      - bosted-network

  sensum-db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sensumpassword
      - MYSQL_DATABASE=sensumDB
      - MYSQL_USER=sensumuser
      - MYSQL_PASSWORD=sensumpassword
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u sensumuser -psensumpassword" ]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - sensum-network

  sensum:
    image: "sensum-image:latest"
    build:
      context: ./Sensum
      dockerfile: Dockerfile
    ports:
      - "6060:6060"
    depends_on:
      sensum-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://sensum-db:3306/sensumDB
      - SPRING_DATASOURCE_USERNAME=sensumuser
      - SPRING_DATASOURCE_PASSWORD=sensumpassword
    networks:
      - sensum-network

  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
    - zookeeper-kafka

  kafka-server1:
    image: 'bitnami/kafka:2.8.0'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data1:/bitnami'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - zookeeper-kafka
      - sensum-network
      - bosted-network

  kafka-server2:
    image: 'bitnami/kafka:2.8.0'
    ports:
      - '9093:9093'
    volumes:
      - 'kafka_data2:/bitnami'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server2:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - zookeeper-kafka
      - sensum-network
      - bosted-network

  kafka:
    image: "kafka-image:latest"
    build:
      context: ./Kafka
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    depends_on:
      - kafka-server1
      - kafka-server2
    networks:
      - zookeeper-kafka
      - sensum-network
      - bosted-network


volumes:
  zookeeper_data:
    driver: local
  kafka_data1:
    driver: local
  kafka_data2:
    driver: local


networks:
  zookeeper-kafka:
  bosted-network:
  sensum-network:
