version: '3'

services:
  bosted-db:
    image: mysql:latest
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=bostedpassword
      - MYSQL_DATABASE=bostedDB
      - MYSQL_USER=bosteduser
      - MYSQL_PASSWORD=bostedpassword
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u bosteduser -pbostedpassword" ]
      interval: 30s
      timeout: 10s
      retries: 5

  bosted:
    image: "bosted-image:latest"
    build:
      context: ./Bosted
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      bosted-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://bosted-db:3306/bostedDB
      - SPRING_DATASOURCE_USERNAME=bosteduser
      - SPRING_DATASOURCE_PASSWORD=bostedpassword
