version: '3'

services:
  client-db:
    image: mysql:latest
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=clientpassword
      - MYSQL_DATABASE=clientdb
      - MYSQL_USER=clientuser
      - MYSQL_PASSWORD=clientpassword
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u clientuser -pclientpassword" ]
      interval: 30s
      timeout: 10s
      retries: 5

  client:
    image: "client-image:latest"
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      client-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://client-db:3306/clientdb
      - SPRING_DATASOURCE_USERNAME=clientuser
      - SPRING_DATASOURCE_PASSWORD=clientpassword
