server:
  port: 8080
Spring:
  application:
    name: Bosted
  datasource:
    username: 'root'
    url: jdbc:mysql://localhost:33061/bostedDB
    password: 'bostedpassword'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update

    show-sql: 'true'