server:
  port: 8080
Spring:
  application:
    name: Bosted
  kafka:
    bootstrap-servers: kafka-server1:9092, kafka-server2:9093
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  datasource:
    username: 'root'
    url: jdbc:mysql://localhost:33061/bostedDB
    password: 'bostedpassword'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update

    show-sql: 'true'