server:
  port: 8080

Spring:
  application:
    name: client
  datasource:
    username: 'root'
    url: jdbc:mysql://localhost:33061/clientdb
    password: 'clientpassword'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update

    show-sql: 'true'